### PR TITLE
Remove Site object when both App and Site present

### PR DESCRIPTION
**Pull request by snahornyi**

### CODE REVIEW

**Review by rpanchyk — APPROVED** [review]

**Comment by muuki88** [comment]
I thought the decision was to not hack around invalid request and issue detailed warnings instead 😅

IMHO there should be at least a warning log for this, or a metric.

**Comment by rpanchyk** [comment]
i'd say we can be more strict here since OpenRTB has constrains on either `app` or `site` but not both.

**Comment by muuki88** [comment]
Exactly that's the point :grin: . The OpenRTB spec exclusively allows one. When some client sends both this is a bug on the client side and IMHO should not be hacked around on the server side, because

- the error isn't really noticed on the client side as the server cleans up
- the behavior is unspecified. Here we prefer app, but why not site?
- no error metrics means that this is completely undetected everywhere. Maybe you less revenue for specific cases, but don't know why

I know that @bretg point was that publishers run prebid version for a very long time without upgrading. So things should be fixed on the server side. I understand that argument, even I lean towards giving publishers incentive to update (hey, things work better!). Another reason to push publishers to update is the maintenance cost this loads on the community as a whole.

So the least what IMHO should be done is introduce an error metric for each account that marks invalid openRTB requests due to `app` and `site` being present.

**Comment by rpanchyk** [comment]
Ok, let's ask @bretg to confirm the new metric :)

**Pull request merged**
