### PR TITLE
Price Floors: Add feature functionality

### PR DESCRIPTION
**Pull request by SerhiiNahornyi**

### CODE REVIEW

**Review by Net-burst — DISMISSED** [review]
LGTM after fixing all remarks from the upcoming joint review.

**Review by And1sS — APPROVED** [review]

**Review by And1sS — APPROVED** [review]

**Review by Net-burst — DISMISSED** [review]
LGTM

**Review by Net-burst — APPROVED** [review]
LGTM, lets go core.

**Review by Net-burst — APPROVED** [review]
LGTM

**Review by Net-burst — APPROVED** [review]

**Pull request merged**
