### PR TITLE
Update App with publisher for Amp request

### PR DESCRIPTION
**Pull request by BraslavskiyAndrey**

### CODE REVIEW

**Review by rpanchyk — APPROVED** [review]

**Review by DGarbar — CHANGES_REQUESTED** [review]
Approve but it is strange that we use app in AMP bc they have similar check 
```
	if req.App != nil {
		errs = []error{errors.New("request.app must not exist in AMP stored requests.")}
		return
	}
```
In GO	
	
Also why we didn't have `auto_gen_source_tid` config flag as they did in Go ?

**Comment by BraslavskiyAndrey** [comment]
> Approve but it is strange that we use app in AMP bc they have similar check
> 
> ```
> 	if req.App != nil {
> 		errs = []error{errors.New("request.app must not exist in AMP stored requests.")}
> 		return
> 	}
> ```
> 
> In GO
> 
> Also why we didn't have `auto_gen_source_tid` config flag as they did in Go ?

We decided to keep publisher look up from app even if for now app can't be present in amp. App null check and publisher lookup has very weak relation in code, so if in future somebody decide to remove app null check, we can forget to add publisher search.

About auto_gen_source_tid. We have config flag responsible for source id generation 'auction.id-generator-type', but it has missleading name and description. But at the same probably we cant replace it safe with other config or rename it, because probably some users can rely on this flag. I think it requires further discussion.

**Comment by DGarbar** [comment]
I have no other question to the PR, so LGTM. 

But I think it is better to point that BidRequest.Source.tid will be updated. (Not bidId like documentation saying) in documentation or change configuration flag. 
@rpanchyk

**Review by DGarbar — APPROVED** [review]

**Comment by rpanchyk** [comment]
Seems updating `app.publisher.id` for AMP doesn't make sense since we have this validation code in `org.prebid.server.auction.AmpRequestFactory#validateStoredBidRequest`:
```
if (bidRequest.getApp() != null) {
    throw new InvalidRequestException("request.app must not exist in AMP stored requests.");
}
```
Closing.

**Pull request closed without merging**
