### PR TITLE
Lunamedia: Pass `site.domain` field

### PR DESCRIPTION
**Pull request by marki1an**

### CODE REVIEW

**Comment by bretg** [comment]
Is this what the Go adapter does? https://github.com/prebid/prebid-server/blob/3789cf91b8e9906d8716000b68817d51971d1559/adapters/lunamedia/lunamedia.go#L164

**Comment by Net-burst** [comment]
@bretg yep, the Go adapter is replacing the domain with an empty string.

**Comment by Net-burst** [comment]
> But the point of the ticket is that they want to receive the domain, not have it nulled out. (?)

Yes... So this means that Go adapter should also get this change.

**Review by Net-burst — APPROVED** [review]
LGTM

**Pull request merged**
